# Generated by Django 4.1.7 on 2023-06-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_productcategory_product_category_and_more'),
        ('central', '0004_alter_websitesetting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_category'),
        ),
    ]
