# Generated by Django 4.1.7 on 2023-06-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_alter_websitesetting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='category',
        ),
    ]
