# Generated by Django 4.1.7 on 2023-06-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_category'),
        ('central', '0008_alter_websitesetting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_category'),
        ),
    ]
